### ISSUE TITLE
使用快捷键的问题

### ISSUE THREAD

**Issue by ABJ1105** [Vant1032/BilibiliVideoCaptureImage#2]
使用快捷键之后转到了一个错误网页
![屏幕截图 2024-05-17 120703](https://github.com/Vant1032/BilibiliVideoCaptureImage/assets/147620625/c83415ea-6eeb-4e5e-b6d4-b52a9be8d432)
并且在本站视频界面右键没有出现下载视频帧的选项（扩展程序也已经安装好了
![屏幕截图 2024-05-17 121017](https://github.com/Vant1032/BilibiliVideoCaptureImage/assets/147620625/cfb5dce1-ab87-48f5-bc68-843ce3de0dad)
![屏幕截图 2024-05-17 121026](https://github.com/Vant1032/BilibiliVideoCaptureImage/assets/147620625/f834fc2a-16af-4ea5-83dd-247b355a86ac)
）

**Comment by Vant1032** [comment]
看了下，是因为图片下载时要调用a.click()来打开下载链接出现了问题，以往chrome是可以直接显示下载的，现在好像不行了，可能跟浏览器版本有关，我想想办法。
另一方面，目前b站右键两次就有复制视频帧功能，我这个插件其实没啥作用了。
